<?php

declare(strict_types=1);

namespace App\Repository\Back;

/**
 * SkillRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SkillRepository extends \Doctrine\ORM\EntityRepository
{

}
